version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "16:00"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 10
    target-branch: master
    reviewers:
      - Josh-Cena
      - GeMini-220
    labels:
      - dependencies
    ignore:
      - dependency-name: sass-loader
        versions:
          - ">= 11.a, < 12"
      - dependency-name: vuetify
        versions:
          - 2.4.11
          - 2.4.4
          - 2.4.5
          - 2.4.7
      - dependency-name: core-js
        versions:
          - 3.10.2
          - 3.9.0
      - dependency-name: eslint-plugin-vue
        versions:
          - 7.6.0
          - 7.7.0
          - 7.9.0
      - dependency-name: "@typescript-eslint/parser"
        versions:
          - 4.14.2
          - 4.15.0
          - 4.15.1
          - 4.15.2
          - 4.16.1
          - 4.17.0
          - 4.20.0
      - dependency-name: "@typescript-eslint/eslint-plugin"
        versions:
          - 4.14.2
          - 4.15.0
          - 4.15.1
          - 4.15.2
          - 4.20.0
      - dependency-name: "@types/node"
        versions:
          - 14.14.24
          - 14.14.25
          - 14.14.26
          - 14.14.28
          - 14.14.30
          - 14.14.36
      - dependency-name: "@vue/cli-service"
        versions:
          - 4.5.12
      - dependency-name: "@vue/cli-plugin-babel"
        versions:
          - 4.5.12
      - dependency-name: "@vue/cli-plugin-vuex"
        versions:
          - 4.5.12
      - dependency-name: "@vue/cli-plugin-router"
        versions:
          - 4.5.12
      - dependency-name: eslint-config-prettier
        versions:
          - 8.1.0
      - dependency-name: vti
        versions:
          - 0.1.0
          - 0.1.1
      - dependency-name: vue-cli-plugin-vuetify
        versions:
          - 2.2.0
          - 2.2.2
      - dependency-name: typescript
        versions:
          - 4.1.4
          - 4.1.5
          - 4.2.2
      - dependency-name: eslint
        versions:
          - 7.19.0
          - 7.21.0
      - dependency-name: sass
        versions:
          - 1.32.6
          - 1.32.7
    commit-message:
      prefix: Dependencies
      include: scope
