export { default as TagsInput } from '@/components/ui/tags-input/TagsInput.vue'
export { default as TagsInputInput } from '@/components/ui/tags-input/TagsInputInput.vue'
export { default as TagsInputItem } from '@/components/ui/tags-input/TagsInputItem.vue'
export { default as TagsInputItemDelete } from '@/components/ui/tags-input/TagsInputItemDelete.vue'
export { default as TagsInputItemText } from '@/components/ui/tags-input/TagsInputItemText.vue'
