-- AlterTable
ALTER TABLE "ActivityRecord" ADD COLUMN     "aTime" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "cTime" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "sTime" DOUBLE PRECISION NOT NULL DEFAULT 0;
