-- CreateEnum
CREATE TYPE "ClubMemberRole" AS ENUM ('PRESIDENT', 'VICE_PRESIDENT', 'MEMBER');

-- CreateEnum
CREATE TYPE "Days" AS ENUM ('SUNDAY', 'MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY');

-- CreateEnum
CREATE TYPE "Periods" AS ENUM ('MORNING', 'ONE', 'TWO', 'THREE', 'FOUR', 'NOON', 'FIVE', 'SIX', 'SEVEN', 'EIGHT', 'NINE', 'AFTERCLASS');

-- CreateTable
CREATE TABLE "User" (
    "id" STRING NOT NULL DEFAULT gen_random_uuid(),
    "clerkUserId" STRING NOT NULL,
    "name" STRING NOT NULL,
    "tsimsStudentId" INT4 NOT NULL,

    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Club" (
    "id" INT4 NOT NULL,
    "name" JSONB NOT NULL,
    "foundedYear" INT4,
    "presidentByTsimsStudentId" INT4 NOT NULL,
    "vicesByTsimsStudentId" INT4[],
    "membersByTsimsStudentId" INT4[],
    "description" JSONB NOT NULL,

    CONSTRAINT "Club_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ClubMembership" (
    "id" STRING NOT NULL DEFAULT gen_random_uuid(),
    "tsimsStudentId" INT4 NOT NULL,
    "name" STRING NOT NULL,
    "clubId" INT4 NOT NULL,
    "role" "ClubMemberRole" NOT NULL,

    CONSTRAINT "ClubMembership_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ActivityRecord" (
    "id" STRING NOT NULL DEFAULT gen_random_uuid(),
    "clubId" INT4 NOT NULL,
    "date" TIMESTAMP(3) NOT NULL,
    "text" STRING NOT NULL,

    CONSTRAINT "ActivityRecord_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ClubRating" (
    "id" STRING NOT NULL DEFAULT gen_random_uuid(),
    "rateBy" STRING NOT NULL,
    "clubId" INT4 NOT NULL,
    "rating" INT4 NOT NULL DEFAULT 0,
    "comment" STRING,
    "ratedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "rateScope" STRING NOT NULL,

    CONSTRAINT "ClubRating_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "GroupInfo" (
    "id" STRING NOT NULL DEFAULT gen_random_uuid(),
    "clubId" INT4 NOT NULL,
    "wechatGroupUrl" STRING NOT NULL,
    "wechatGroupExpiration" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "GroupInfo_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ClassroomData" (
    "id" STRING NOT NULL DEFAULT gen_random_uuid(),
    "name" STRING NOT NULL,
    "alias" STRING,
    "size" INT4,

    CONSTRAINT "ClassroomData_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ReservationRecord" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "creationTimestamp" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "userId" STRING NOT NULL,
    "day" "Days" NOT NULL,
    "period" "Periods" NOT NULL,
    "classroomId" STRING NOT NULL,
    "clubId" INT4 NOT NULL,
    "note" STRING,

    CONSTRAINT "ReservationRecord_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "_ActivityRecordToClubMembership" (
    "A" STRING NOT NULL,
    "B" STRING NOT NULL
);

-- CreateIndex
CREATE UNIQUE INDEX "User_clerkUserId_key" ON "User"("clerkUserId");

-- CreateIndex
CREATE UNIQUE INDEX "User_tsimsStudentId_key" ON "User"("tsimsStudentId");

-- CreateIndex
CREATE UNIQUE INDEX "ClubMembership_tsimsStudentId_clubId_key" ON "ClubMembership"("tsimsStudentId", "clubId");

-- CreateIndex
CREATE UNIQUE INDEX "ClubRating_clubId_rateBy_rateScope_key" ON "ClubRating"("clubId", "rateBy", "rateScope");

-- CreateIndex
CREATE UNIQUE INDEX "GroupInfo_clubId_key" ON "GroupInfo"("clubId");

-- CreateIndex
CREATE UNIQUE INDEX "ReservationRecord_id_key" ON "ReservationRecord"("id");

-- CreateIndex
CREATE UNIQUE INDEX "ReservationRecord_classroomId_day_period_key" ON "ReservationRecord"("classroomId", "day", "period");

-- CreateIndex
CREATE UNIQUE INDEX "_ActivityRecordToClubMembership_AB_unique" ON "_ActivityRecordToClubMembership"("A", "B");

-- CreateIndex
CREATE INDEX "_ActivityRecordToClubMembership_B_index" ON "_ActivityRecordToClubMembership"("B");

-- AddForeignKey
ALTER TABLE "ClubMembership" ADD CONSTRAINT "ClubMembership_clubId_fkey" FOREIGN KEY ("clubId") REFERENCES "Club"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ActivityRecord" ADD CONSTRAINT "ActivityRecord_clubId_fkey" FOREIGN KEY ("clubId") REFERENCES "Club"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ClubRating" ADD CONSTRAINT "ClubRating_rateBy_fkey" FOREIGN KEY ("rateBy") REFERENCES "User"("clerkUserId") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ClubRating" ADD CONSTRAINT "ClubRating_clubId_fkey" FOREIGN KEY ("clubId") REFERENCES "Club"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "GroupInfo" ADD CONSTRAINT "GroupInfo_clubId_fkey" FOREIGN KEY ("clubId") REFERENCES "Club"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ReservationRecord" ADD CONSTRAINT "ReservationRecord_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ReservationRecord" ADD CONSTRAINT "ReservationRecord_classroomId_fkey" FOREIGN KEY ("classroomId") REFERENCES "ClassroomData"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ReservationRecord" ADD CONSTRAINT "ReservationRecord_clubId_fkey" FOREIGN KEY ("clubId") REFERENCES "Club"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_ActivityRecordToClubMembership" ADD CONSTRAINT "_ActivityRecordToClubMembership_A_fkey" FOREIGN KEY ("A") REFERENCES "ActivityRecord"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_ActivityRecordToClubMembership" ADD CONSTRAINT "_ActivityRecordToClubMembership_B_fkey" FOREIGN KEY ("B") REFERENCES "ClubMembership"("id") ON DELETE CASCADE ON UPDATE CASCADE;
