#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

## Run lint-staged
yarn run lint-staged

## If there's change to JS files, run type-check
FILES=$(git diff --cached --name-only --diff-filter=ACMR "*.js" "*.ts" "*.vue" | sed 's| |\\ |g')

# Quit if no action needed
[ -z "$FILES" ] && exit 0

# It is run here, since vti-diagnose does not accept file arguments
# and thus should not be run with lint-staged
yarn type-check
