name: Sync from staging to prod
on:
  push:
    tags:        
      - '**'
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge staging -> prod
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: next
          target_branch: prod
          github_token: ${{ secrets.GITHUB_TOKEN }}
